services:
    - type: web
      name: larashop
      runtime: docker
      plan: free
      branch: main
      healthCheckPath: /up
      autoDeploy: true

      envVars:
          - key: APP_ENV
            value: production

          - key: APP_DEBUG
            value: "false"

          - key: APP_KEY
            generateValue: true

          - key: DB_CONNECTION
            value: sqlite

          - key: DB_DATABASE
            value: /var/www/html/database/database.sqlite

          - key: FILESYSTEM_DISK
            value: public

          - key: RUN_MIGRATIONS
            value: "true"

          - key: RUN_SEEDERS
            value: "true"

          - key: LOG_CHANNEL
            value: stderr

          - key: LOG_LEVEL
            value: debug
