<?php 

namespace App\Services\Report;

use App\Models\User;
use App\Models\Product;
use App\Models\OrderLedger As Order;

use App\Enums\OrderStatus;

use Illuminate\Support\Facades\DB;

class ReportService
{
	
	// Get public statics about the system
	public function getSummaryMetrics(): array
	{
		return [
			'total_revenue' => Order::where('status', OrderStatus::PAID)
									->orWhere('status', OrderStatus::SHIPPED)
									->sum('total_amount'),
			'total_orders' 	=> Order::count(),
			'total_users'	=> User::count(),
			
			// Count products where the sum of all variant stocks is less than 5
        	'low_stock'     => Product::query()
            							->withSum('productDetails as total_stock', 'stock')
            							->having('total_stock', '<', 5)
            							->count(),
		];
	}

	// Get the count of each order status individual like ['pending' => 15]
	public function getOrderStatusBreakdown(): array
	{
		return Order::query()

					// targets the status column in your orders database table and counts 
					// the total rows associated with each unique status value
					->select('status', DB::raw('count(*) as count'))
					->groupBy('status')

					// extracts the database query results into a key-value pair format where
					 // the status name is the key and the total count is the value.
					->pluck('count', 'status')
					->toArray();
	}

	/*
	* calculate which products have generated the most total money (revenue) across all 
	* completed orders, and returns the top items (defaulting to the top 5).
	**/
	public function getTopSellingProducts(int $limit = 5)
	{
		return DB::table('order_items')
			 	 ->join('products', 'order_items.product_details_id', '=', 'products.id')
			 	 ->select(
			 	 	'products.name',
			 	 	
			 	 	// sums up every single unit of that product ever purchased across all orders
			 	 	DB::raw('SUM(order_items.quantity) as total_qty'),
			 	 	
			 	 	// calculates the total dollar amount generated by multiplying the unit price 
			 	 	// by quantity sold for each purchase and adding them all together
                	DB::raw('SUM(order_items.quantity * order_items.price) as total_revenue')
			 	 )
			 	 ->groupBy('products.id', 'products.name')
			 	 ->orderByDesc('total_revenue')
			 	 ->limit($limit)
			 	 ->get();
	}

}
